version: '2'
services:
    influx:
        image: influxdb:alpine
        ports:
            - "8086:8086"
        logging:
            driver: json-file
            options:
                max-size: "100m"
                max-file: "3"

    db:
        image: postgres:alpine
        environment:
            POSTGRES_DB: chariot
            POSTGRES_USER: chariot
            POSTGRES_PASSWORD: chariot
        logging:
            driver: json-file
            options:
                max-size: "100m"
                max-file: "3"

    app:
        build: src/app
        links:
            - db
            - influx
        volumes:
            - ./src/app:/app
            - /media
            - /static
        logging:
            driver: json-file
            options:
                max-size: "100m"
                max-file: "3"

    web:
        restart: always
        image: nginx:alpine
        container_name: chariot_web
        ports:
            - "80:80"
            - "443:443"
        links:
            - app
        volumes:
            - ./src/conf/nginx${CONF_TAG}.conf:/etc/nginx/nginx.conf:ro
            - ./cert/certs:/cert
            - ./src/www:/www
        volumes_from:
            - app
        logging:
            driver: json-file
            options:
                max-size: "100m"
                max-file: "3"

    cert:
        build: src/cert
        links:
            - web
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock
            - ./cert:/etc/letsencrypt
        environment:
            - DOMAINS
            - CHECK_FREQ=10
            - SERVER_CONTAINER=chariot_web